CREATE TABLE teachers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  teacher_name TEXT NOT NULL unique,
  email TEXT NOT NULL unique,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);