CREATE TABLE groupings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  grouping_name TEXT NOT NULL,
  groupings JSONB NOT NULL,
  data JSONB NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  teacher_id INTEGER REFERENCES teachers(id),
  class_id INTEGER REFERENCES classes(id)
);