CREATE TABLE groupings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  grouping_name TEXT NOT NULL,
  groupings JSONB NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  teacher_id REFERENCES teachers(id),
  class_id REFERENCES classes(id)
);